// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjcdCZirgOtq4oHa6vdhL7HQeta2C96PM',
    appId: '1:839121959872:web:426f4d052c9be05da82625',
    messagingSenderId: '839121959872',
    projectId: 'flutterfire-lostnfound',
    authDomain: 'flutterfire-lostnfound.firebaseapp.com',
    storageBucket: 'flutterfire-lostnfound.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC85pmaJGgTgZ5clLY1_vAJVx_EHESd4xE',
    appId: '1:839121959872:android:86a580698e2960a4a82625',
    messagingSenderId: '839121959872',
    projectId: 'flutterfire-lostnfound',
    storageBucket: 'flutterfire-lostnfound.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd8bs1a29DOEqa6yYp59pEhgT-r3-tDdE',
    appId: '1:839121959872:ios:e3f41e1b2dc5645aa82625',
    messagingSenderId: '839121959872',
    projectId: 'flutterfire-lostnfound',
    storageBucket: 'flutterfire-lostnfound.appspot.com',
    iosClientId: '839121959872-gre95s57m0k48gifg526b4lt8nf8a945.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusLostNFound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd8bs1a29DOEqa6yYp59pEhgT-r3-tDdE',
    appId: '1:839121959872:ios:e3f41e1b2dc5645aa82625',
    messagingSenderId: '839121959872',
    projectId: 'flutterfire-lostnfound',
    storageBucket: 'flutterfire-lostnfound.appspot.com',
    iosClientId: '839121959872-gre95s57m0k48gifg526b4lt8nf8a945.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusLostNFound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjcdCZirgOtq4oHa6vdhL7HQeta2C96PM',
    appId: '1:839121959872:web:61d66f31d66c66d9a82625',
    messagingSenderId: '839121959872',
    projectId: 'flutterfire-lostnfound',
    authDomain: 'flutterfire-lostnfound.firebaseapp.com',
    storageBucket: 'flutterfire-lostnfound.appspot.com',
  );
}
